# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photomosaic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Mosaic',
        ),
    ]
