# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 13:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photomosaic', '0002_auto_20171203_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=b'/media/photos'), upload_to=b'')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
