# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photomosaic', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='text',
        ),
    ]
