# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photomosaic', '0004_auto_20171205_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
